language: python
python:
  - "3.5"

sudo: required
dist: precise
addons:
    postgresql: "9.5"
services:
    - postgresql

install: "pip install -r requirements/development.txt"

script: py.test --cov=app/api/controllers tests/