language: python
python:
  - "3.5"

env:
  - DATABASE_URL = postgresql://postgres@127.0.0.1/bulk_upload

sudo: false
addons:
    postgresql: "9.4"
services:
    - postgresql

before_script:
- psql -c 'create database bulk_upload;' -U postgres

install: "pip install -r requirements/development.txt"

script: py.test --cov=app/api/controllers tests/