sudo: required
dist: trusty

language: python

python:
  - "3.5"

addons:
    postgresql: "9.5"

before_script:
  - psql -c 'create database "bulk_upload";' -U postgres

before_install:
  - export DATABASE_URL="postgresql://postgres@localhost/bulk_upload"

install: "pip install -r requirements/development.txt"

script: py.test --cov=app/api/controllers tests/